In [3]:
import numpy as np


In [7]:
x1 = np.random.randint(10, size =(5))
x1


array([7, 1, 2, 3, 2])

In [9]:
x1.size

5

In [11]:
x1.itemsize

4

In [13]:
x1.ndim

1

In [19]:
x1.nbytes

20

In [21]:
x1.shape



(5,)

In [28]:
x2 = np.random.randint (10, size=(3,4))
x2

array([[7, 0, 6, 6],
       [4, 8, 1, 8],
       [8, 3, 8, 5]])

In [30]:
x2.size

12

In [32]:
x2.ndim

2

In [34]:
x2.shape


(3, 4)

In [36]:
x2.nbytes

48

In [38]:
x2.itemsize

4

In [45]:
x5= np.arange (0,49)
x5 = x5.reshape (7,7)
x5

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47, 48]])

In [47]:
x5[1::3, ::4]

array([[ 7, 11],
       [28, 32]])

In [61]:
# x5[2:4, 1]
# x5[::2,0:2] #(Step, meaning jumping)jumping from index 0, then jumping index 1 in  loop // second opt is for col meaning start from index 0 and stop from index 1 (Not step)
# x5[1::3, 4::2]
# x5[1::3,4::2]


array([15, 22])

In [63]:
x5[-3:-1, ::-2]

array([[34, 32, 30, 28],
       [41, 39, 37, 35]])

In [244]:
x4 = np.random.randint(100, size =(20)) 
x4 = x4.reshape (4,5)
x4[0:2]
# x4[:3, -1:-3]
# x4

array([[43, 87, 97, 13, 85],
       [93,  1, 64, 90, 94]])

In [129]:
x4[:3, -2:]

array([[71, 46],
       [17, 25],
       [32, 95]])

In [141]:
x6 = np.array ([[0,1,1,0,0],
                [1,1,1,0,0],
                [0,0,1,0,1],
                [1,0,1,1,0],
                [1,0,0,0,1],
               ])
x6

array([[0, 1, 1, 0, 0],
       [1, 1, 1, 0, 0],
       [0, 0, 1, 0, 1],
       [1, 0, 1, 1, 0],
       [1, 0, 0, 0, 1]])

In [152]:
x6 =x6.reshape(25)
x6

array([0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       0, 0, 1])

In [181]:
x6[0::1]

array([1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0])

In [186]:
x6 = x6.reshape(3,4)
x6

array([[1, 0, 1, 1],
       [0, 0, 0, 1],
       [1, 0, 0, 0]])

In [268]:
x7= np.random.randint(10,50, size = (3,4,5))
x7

array([[[33, 13, 20, 34, 48],
        [29, 31, 48, 25, 25],
        [10, 21, 19, 37, 16],
        [16, 38, 15, 38, 11]],

       [[21, 24, 48, 16, 12],
        [14, 47, 45, 40, 14],
        [49, 15, 47, 40, 19],
        [20, 49, 19, 24, 24]],

       [[30, 22, 12, 28, 30],
        [28, 45, 30, 13, 45],
        [31, 31, 45, 43, 33],
        [27, 27, 14, 30, 16]]])

In [270]:
x7i = x7.reshape(6,10)
x7i

array([[33, 13, 20, 34, 48, 29, 31, 48, 25, 25],
       [10, 21, 19, 37, 16, 16, 38, 15, 38, 11],
       [21, 24, 48, 16, 12, 14, 47, 45, 40, 14],
       [49, 15, 47, 40, 19, 20, 49, 19, 24, 24],
       [30, 22, 12, 28, 30, 28, 45, 30, 13, 45],
       [31, 31, 45, 43, 33, 27, 27, 14, 30, 16]])

In [272]:
x7i [-1:: , ::]

array([[31, 31, 45, 43, 33, 27, 27, 14, 30, 16]])

In [274]:
x7 [:, :, 2]

array([[20, 48, 19, 15],
       [48, 45, 47, 19],
       [12, 30, 45, 14]])

In [39]:
x1a = np.random.randint(100,200, size=(60)) 
x1a

array([177, 160, 151, 154, 118, 116, 186, 173, 175, 167, 151, 194, 193,
       170, 124, 160, 146, 141, 111, 127, 183, 188, 108, 187, 112, 173,
       116, 197, 173, 103, 139, 169, 119, 198, 178, 120, 177, 175, 130,
       114, 176, 107, 121, 142, 122, 147, 119, 189, 185, 170, 117, 129,
       170, 138, 128, 142, 163, 150, 185, 130])

In [45]:
x1a =x1a.reshape(3,4,5)
x1a

array([[[177, 160, 151, 154, 118],
        [116, 186, 173, 175, 167],
        [151, 194, 193, 170, 124],
        [160, 146, 141, 111, 127]],

       [[183, 188, 108, 187, 112],
        [173, 116, 197, 173, 103],
        [139, 169, 119, 198, 178],
        [120, 177, 175, 130, 114]],

       [[176, 107, 121, 142, 122],
        [147, 119, 189, 185, 170],
        [117, 129, 170, 138, 128],
        [142, 163, 150, 185, 130]]])

In [105]:
x1a[0:1,-4:-3,:]
# x1a

array([[[177, 160, 151, 154, 118]]])

In [89]:
x1a[:,3:4,:]

array([[[160, 146, 141, 111, 127]],

       [[120, 177, 175, 130, 114]],

       [[142, 163, 150, 185, 130]]])

In [109]:
x2a = np.arange(10,31) 
x2a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30])

In [125]:
x2a[::3]

array([10, 13, 16, 19, 22, 25, 28])

In [129]:
x2af = np.flip(x2a)
x2af

array([30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14,
       13, 12, 11, 10])

In [131]:
x2af[16:]

array([14, 13, 12, 11, 10])

In [135]:
x2afs = x2af[16:]
x2afs

array([14, 13, 12, 11, 10])

In [137]:
t_x2afs = np.sum(x2afs)
t_x2afs

60

In [9]:
x3a =np.random.randint(1,100, size=(5,5))
x3a

array([[ 5, 50, 68, 70, 27],
       [43, 43, 51, 31, 12],
       [81, 18, 31, 82, 49],
       [84, 80, 46, 13, 21],
       [41, 70, 11, 30, 90]])

In [11]:
x3ar=x3a.reshape(25)
x3ar

array([ 5, 50, 68, 70, 27, 43, 43, 51, 31, 12, 81, 18, 31, 82, 49, 84, 80,
       46, 13, 21, 41, 70, 11, 30, 90])

In [13]:
x3a[1::2]

array([[43, 43, 51, 31, 12],
       [84, 80, 46, 13, 21]])

In [15]:
x3a[x3a >= 50] = -1
x3a

array([[ 5, -1, -1, -1, 27],
       [43, 43, -1, 31, 12],
       [-1, 18, 31, -1, 49],
       [-1, -1, 46, 13, 21],
       [41, -1, 11, 30, -1]])

In [23]:
x4a = np.random.randint (24, size=(4,3,2))
x4a

array([[[11, 19],
        [ 1, 13],
        [14, 17]],

       [[ 7, 12],
        [15,  0],
        [ 8,  8]],

       [[10,  2],
        [ 8,  6],
        [11,  6]],

       [[ 9,  6],
        [11, 17],
        [14,  4]]])

In [63]:
x4a[-3:-2 ,-3:-2 ,0:1 ]

array([[[7]]])

In [65]:
x4a[0:2 ,: ,: ]

array([[[11, 19],
        [ 1, 13],
        [14, 17]],

       [[ 7, 12],
        [15,  0],
        [ 8,  8]]])

In [69]:
x4a = x4a.reshape(2,6,2)
x4a

array([[[11, 19],
        [ 1, 13],
        [14, 17],
        [ 7, 12],
        [15,  0],
        [ 8,  8]],

       [[10,  2],
        [ 8,  6],
        [11,  6],
        [ 9,  6],
        [11, 17],
        [14,  4]]])

In [12]:
x1d= np.random.randint (1,100, size = (30))
x1d

array([24, 22, 62, 73, 42, 43,  2, 30, 11, 94, 98, 63, 92, 91, 62, 88, 85,
       86, 97, 51, 55, 74, 62, 70, 42,  6, 62, 80, 77, 37])

In [22]:
xw,xy,xz = np.split(x1d, (10,20))
print(xw,xy,xz)

[24 22 62 73 42 43  2 30 11 94] [98 63 92 91 62 88 85 86 97 51] [55 74 62 70 42  6 62 80 77 37]


Array Concatenation cw

In [31]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])
# arr1
print(arr1)
arr2

[1 2 3 4 5]


array([ 6,  7,  8,  9, 10])

In [37]:
np.concatenate([arr1,arr2], axis=0)


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [49]:
# np.concatenate([arr1,arr2], axis=1)
np.add(arr1,arr2)

array([ 7,  9, 11, 13, 15])

In [61]:
arrx = np.vstack([arr1,arr2])
print (arrx)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [69]:
arr1_2D = np.array([[1,2],[3,4],[5,6]])
arr2_2D = np.array([[7,8],[9,10],[11,12]])
print(arr1_2D)
arr2_2D

[[1 2]
 [3 4]
 [5 6]]


array([[ 7,  8],
       [ 9, 10],
       [11, 12]])

In [71]:
np.concatenate([arr1_2D,arr2_2D], axis=0)


array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [73]:
np.concatenate([arr1_2D,arr2_2D], axis=1)

array([[ 1,  2,  7,  8],
       [ 3,  4,  9, 10],
       [ 5,  6, 11, 12]])

In [81]:
r1d = np.linspace(0,1, 6)
r1d

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [83]:
r1p =np.linspace(0,2*np.pi, 10)
r1p

array([0.        , 0.6981317 , 1.3962634 , 2.0943951 , 2.7925268 ,
       3.4906585 , 4.1887902 , 4.88692191, 5.58505361, 6.28318531])

In [87]:
np.sin(r1p)

array([ 0.00000000e+00,  6.42787610e-01,  9.84807753e-01,  8.66025404e-01,
        3.42020143e-01, -3.42020143e-01, -8.66025404e-01, -9.84807753e-01,
       -6.42787610e-01, -2.44929360e-16])

In [85]:
r1a= np.linspace(-5,-1, 10)
r1a

array([-5.        , -4.55555556, -4.11111111, -3.66666667, -3.22222222,
       -2.77777778, -2.33333333, -1.88888889, -1.44444444, -1.        ])

In [89]:
np.abs(r1a)

array([5.        , 4.55555556, 4.11111111, 3.66666667, 3.22222222,
       2.77777778, 2.33333333, 1.88888889, 1.44444444, 1.        ])

In [93]:
s1 = np.random.randint(10,50, size=(4,5))
s1

array([[41, 49, 41, 27, 32],
       [21, 11, 44, 12, 17],
       [22, 44, 35, 17, 41],
       [43, 30, 21, 39, 29]])

In [95]:
s1.sum(axis=0)

array([127, 134, 141,  95, 119])

In [97]:
s1.sum(axis=1)

array([190, 105, 159, 162])

In [99]:
np.mean(s1)

30.8

In [101]:
np.std(s1)

11.491736161259533

In [105]:
s6 = np.random.randint(10,50, size=(3,4))
s6

array([[18, 29, 36, 33],
       [16, 28, 39, 38],
       [14, 22, 38, 44]])

In [115]:
s7 = np.array([100,101,102,103])
# np.add(s6,s7)

In [127]:
s8= np.vstack([s6,s7])
s8

array([[ 18,  29,  36,  33],
       [ 16,  28,  39,  38],
       [ 14,  22,  38,  44],
       [100, 101, 102, 103]])

In [172]:
s8[1]

array([16, 28, 39, 38])

In [178]:
s2d= np.random.randint(15, size=(5,3))
s2d

array([[ 7,  8, 13],
       [12,  4,  4],
       [ 7,  5,  7],
       [10,  2, 12],
       [14,  3, 13]])

In [180]:
s2d.reshape(15)

array([ 7,  8, 13, 12,  4,  4,  7,  5,  7, 10,  2, 12, 14,  3, 13])

In [182]:
s2d.reshape(3,5)

array([[ 7,  8, 13, 12,  4],
       [ 4,  7,  5,  7, 10],
       [ 2, 12, 14,  3, 13]])

In [192]:
ar1 = np.array([10,20,30])
ar2 = np.array([40,50,60])

np.concatenate([ar1,ar2], axis=0)

array([10, 20, 30, 40, 50, 60])

In [194]:
np.concatenate([ar1,ar2], axis=1)

AxisError: axis 1 is out of bounds for array of dimension 1

In [196]:
ar1_2d =np.array([[1,2],[3,4]])
ar2_2d =np.array([[5,6],[7,8]])

In [198]:
np.concatenate([ar1_2d,ar2_2d], axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [200]:
np.concatenate([ar1_2d,ar2_2d], axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [210]:
c1= np.random.randint(0,6, size=(2,3))
c2= np.random.randint(7,12, size=(2,3))
print (c1)
c2

[[3 0 4]
 [3 0 2]]


array([[ 7,  7,  7],
       [10,  7, 10]])

In [212]:
np.concatenate([c1,c2], axis=0)

array([[ 3,  0,  4],
       [ 3,  0,  2],
       [ 7,  7,  7],
       [10,  7, 10]])

In [214]:
np.concatenate([c1,c2], axis=1)

array([[ 3,  0,  4,  7,  7,  7],
       [ 3,  0,  2, 10,  7, 10]])

In [7]:
a1a = np.random.randint(1,100, size=(10))
a1a

array([50, 97, 33, 89,  9, 48, 55, 89, 96, 51])

In [9]:
np.sort(a1a)

array([ 9, 33, 48, 50, 51, 55, 89, 89, 96, 97])

In [11]:
np.sort(a1a)[::-1]

array([97, 96, 89, 89, 55, 51, 50, 48, 33,  9])

In [13]:
np.partition(a1a,2)

array([ 9, 33, 48, 89, 50, 97, 55, 89, 96, 51])

Broadcasting Assignment

In [15]:
m1= np.random.randint(1,9, size=(3,3))
m1

array([[6, 4, 2],
       [3, 1, 8],
       [4, 4, 3]])

In [21]:
b= np.array([10,20,30])
b

array([10, 20, 30])

In [29]:
m1+b

array([[16, 24, 32],
       [13, 21, 38],
       [14, 24, 33]])

In [45]:
a11=np.ones((4,4))
a11

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [49]:
c=np.array([1, 2, 3, 4])
c

array([1, 2, 3, 4])

In [51]:
a11+c

array([[2., 3., 4., 5.],
       [2., 3., 4., 5.],
       [2., 3., 4., 5.],
       [2., 3., 4., 5.]])

Fancy Index

In [59]:
fi=np.random.randint(1,50, size=(20))
fi 

array([49, 27, 14, 23, 30, 29, 28, 35, 11, 24, 21, 41, 19, 32,  3, 24, 35,
       18,  8, 49])

In [65]:
fi[[2,4,6,9,13,15,17,18]]


array([14, 30, 28, 24, 32, 24, 18,  8])

In [69]:
fi[[0,1,4,5,6,7,11,13,16,19]]

array([49, 27, 30, 29, 28, 35, 41, 32, 35, 49])

Aggregation

In [73]:
ag=np.random.randint(1,100, size=(5,4))
ag

array([[32, 65, 72, 79],
       [16, 30, 54, 54],
       [99, 72,  2, 18],
       [11, 54, 90, 18],
       [84, 48, 60, 77]])

In [77]:
np.mean(ag)

51.75

In [80]:
np.sum(ag)

1035

In [82]:
np.max(ag)

99

In [84]:
np.min(ag)

2

In [86]:
np.mean(ag, axis=1)

array([48.4, 53.8, 55.6, 49.2])

In [90]:
np.sum(ag,axis=1)

array([248, 154, 191, 173, 269])

Sorting and Partitioning

In [96]:
d1=np.random.randint(1,200,size=(15))
d1

array([ 58,  37,  60, 110,   1, 177,  86, 151, 132,  26,  79,   3, 101,
        70, 137])

In [108]:
d2=np.argsort(d1)
d2

array([ 4, 11,  9,  1,  0,  2, 13, 10,  6, 12,  3,  8, 14,  7,  5],
      dtype=int64)

In [116]:
d3=np.sort(d2)
d3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
      dtype=int64)

In [123]:
d6=np.random.randint(1,100,size=(6,6))
d6

array([[87, 35, 75, 78,  4, 94],
       [82, 56, 15, 93, 49, 24],
       [54, 53, 75, 88, 38, 38],
       [37, 62, 38, 47, 93, 61],
       [22, 70, 56, 52, 55, 87],
       [38, 86, 37, 35, 22, 85]])

In [125]:
np.sort(d6)

array([[ 4, 35, 75, 78, 87, 94],
       [15, 24, 49, 56, 82, 93],
       [38, 38, 53, 54, 75, 88],
       [37, 38, 47, 61, 62, 93],
       [22, 52, 55, 56, 70, 87],
       [22, 35, 37, 38, 85, 86]])

In [135]:
np.sort(d6)[::-1]

array([[22, 35, 37, 38, 85, 86],
       [22, 52, 55, 56, 70, 87],
       [37, 38, 47, 61, 62, 93],
       [38, 38, 53, 54, 75, 88],
       [15, 24, 49, 56, 82, 93],
       [ 4, 35, 75, 78, 87, 94]])

In [141]:
u = np.linspace(0,1,20)
u

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [151]:
np.partition(u,15)

array([0.05263158, 0.        , 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.57894737, 0.52631579, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [155]:
ar4 = np.random.randint(1,14, size=(4,4))
ar4

array([[13,  5,  1,  7],
       [ 5, 10,  8, 10],
       [ 8, 12,  4, 12],
       [ 4,  8,  7,  9]])

In [163]:
ar4i = np.mean(ar4, axis=1)

In [192]:
ar4-ar4i

array([[ 6.5 , -3.25, -8.  ,  0.  ],
       [-1.5 ,  1.75, -1.  ,  3.  ],
       [ 1.5 ,  3.75, -5.  ,  5.  ],
       [-2.5 , -0.25, -2.  ,  2.  ]])

In [194]:
ar5 = np.random.randint(1,50, size=(3,5))
ar5

array([[35, 43, 27,  3, 45],
       [34, 41, 24, 24, 31],
       [ 9, 45, 41,  6, 34]])

In [187]:
ar5i = np.max(ar5, axis = 0)
ar5i

array([33, 35, 49, 48, 42])

In [189]:
ar5/ar5i

array([[0.72727273, 1.        , 0.69387755, 0.54166667, 0.80952381],
       [0.42424242, 0.17142857, 1.        , 0.79166667, 0.42857143],
       [1.        , 0.25714286, 0.46938776, 1.        , 1.        ]])

In [198]:
id= np.identity(5)
id

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [23]:
id [0,1,2,3,4]


TypeError: list indices must be integers or slices, not tuple

In [28]:
ri = np.random.randint(1,500, size=(25))
ri

array([ 16, 289, 232, 259,  78, 202, 211, 311, 105, 224, 337, 447, 241,
       185, 141, 372, 254, 437, 378, 145,  37, 142, 281, 111,  69])

In [64]:
    for j in ri:
     if j%2 != 0:
         j is True
         print (j)


289
259
211
311
105
337
447
241
185
141
437
145
37
281
111
69


In [69]:
num = np.arange(1,37)
num

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36])

In [73]:
s_num=num**2
s_num

array([   1,    4,    9,   16,   25,   36,   49,   64,   81,  100,  121,
        144,  169,  196,  225,  256,  289,  324,  361,  400,  441,  484,
        529,  576,  625,  676,  729,  784,  841,  900,  961, 1024, 1089,
       1156, 1225, 1296])

In [81]:
def checkerboard(shape):
    return np.indices(shape).sum(axis=0) % 2

checkerboard ()

TypeError: checkerboard() missing 1 required positional argument: 'shape'